Going back to Bash.

diff --git a/private_dot_iterm2/executable_imgcat b/private_dot_iterm2/executable_imgcat
--- a/private_dot_iterm2/executable_imgcat
+++ b/private_dot_iterm2/executable_imgcat
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
 set -o pipefail
 
@@ -7,7 +7,7 @@ set -o pipefail
 # only accepts ESC backslash for ST. We use TERM instead of TMUX because TERM
 # gets passed through ssh.
 function print_osc() {
-    if [[ $TERM == screen* || $TERM == tmux* ]]; then
+    if [[ $TERM == screen* ]]; then
         printf "\033Ptmux;\033\033]"
     else
         printf "\033]"
@@ -16,7 +16,7 @@ function print_osc() {
 
 # More of the tmux workaround described above.
 function print_st() {
-    if [[ $TERM == screen* || $TERM == tmux* ]]; then
+    if [[ $TERM == screen* ]]; then
         printf "\a\033\\"
     else
         printf "\a"
@@ -60,7 +60,6 @@ function b64_decode() {
 #   width: set output width of the image in character cells, pixels or percent
 #   height: set output height of the image in character cells, pixels or percent
 #   preserve_aspect_ratio: 0 or 1, if set to 1, fill the specified width and height as much as possible without stretching the image
-#   file: Empty string or file type like "application/json" or ".js".
 function print_image() {
     print_osc
     printf "1337;File=inline=%s" "$2"
@@ -69,7 +68,6 @@ function print_image() {
     [ -n "$5" ] && printf ";width=%s" "$5"
     [ -n "$6" ] && printf ";height=%s" "$6"
     [ -n "$7" ] && printf ";preserveAspectRatio=%s" "$7"
-    [ -n "$8" ] && printf ";type=%s" "$8"
     printf ":%s" "$3"
     print_st
     printf '\n'
@@ -87,7 +85,7 @@ function errcho() {
 
 function show_help() {
     errcho
-    errcho "Usage: imgcat [-p] [-n] [-W width] [-H height] [-r] [-s] [-u] [-t file-type] [-f] filename ..."
+    errcho "Usage: imgcat [-p] [-n] [-W width] [-H height] [-r] [-s] [-u] [-f] filename ..."
     errcho "       cat filename | imgcat [-W width] [-H height] [-r] [-s]"
     errcho
     errcho "Display images inline in the iTerm2 using Inline Images Protocol"
@@ -99,7 +97,6 @@ function show_help() {
     errcho "    -n, --no-print                  Disable printing of filename or URL after each image"
     errcho "    -u, --url                       Interpret following filename arguments as remote URLs"
     errcho "    -f, --file                      Interpret following filename arguments as regular Files"
-    errcho "    -t, --type file-type            Provides a type hint"
     errcho "    -r, --preserve-aspect-ratio     When scaling image preserve its original aspect ratio"
     errcho "    -s, --stretch                   Stretch image to specified width and height (this option is opposite to -r)"
     errcho "    -W, --width N                   Set image width to N character cells, pixels or percent (see below)"
@@ -112,24 +109,18 @@ function show_help() {
     errcho "        N%     percent of the session's width or height"
     errcho "        auto   the image's inherent size will be used to determine an appropriate dimension"
     errcho
-    errcho "    If a type is provided, it is used as a hint to disambiguate."
-    errcho "    The file type can be a mime type like text/markdown, a language name like Java, or a file extension like .c"
-    errcho "    The file type can usually be inferred from the extension or its contents. -t is most useful when"
-    errcho "    a filename is not available, such as whe input comes from a pipe."
-    errcho
     errcho "Examples:"
     errcho
     errcho "    $ imgcat -W 250px -H 250px -s avatar.png"
     errcho "    $ cat graph.png | imgcat -W 100%"
     errcho "    $ imgcat -p -W 500px -u http://host.tld/path/to/image.jpg -W 80 -f image.png"
     errcho "    $ cat url_list.txt | xargs imgcat -p -W 40 -u"
-    errcho "    $ imgcat -t application/json config.json"
     errcho
 }
 
 function check_dependency() {
     if ! (builtin command -V "$1" >/dev/null 2>&1); then
-        error "missing dependency: can't find $1"
+        echo "imgcat: missing dependency: can't find $1" 1>&2
         exit 1
     fi
 }
@@ -159,7 +150,6 @@ fi
 
 check_dependency base64
 check_dependency wc
-file_type=""
 
 # Look for command line flags.
 while [ $# -gt 0 ]; do
@@ -184,13 +174,13 @@ while [ $# -gt 0 ]; do
         height="$2"
         shift
         ;;
-    -r | --r | --preserve-aspect-ratio)
+    -r | --R | --preserve-aspect-ratio)
         preserve_aspect_ratio=1
         ;;
-    -s | --s | --stretch)
+    -s | --S | --stretch)
         preserve_aspect_ratio=0
         ;;
-    -f | --f | --file)
+    -f | --F | --file)
         has_stdin=f
         is_url=f
         ;;
@@ -199,10 +189,6 @@ while [ $# -gt 0 ]; do
         has_stdin=f
         is_url=t
         ;;
-    -t | --t | --type)
-         file_type="$2"
-         shift
-         ;;
     -*)
         error "Unknown option flag: $1"
         show_help
@@ -221,7 +207,7 @@ while [ $# -gt 0 ]; do
             exit 2
         fi
         has_stdin=f
-        print_image "$1" 1 "$encoded_image" "$print_filename" "$width" "$height" "$preserve_aspect_ratio" "$file_type"
+        print_image "$1" 1 "$encoded_image" "$print_filename" "$width" "$height" "$preserve_aspect_ratio"
         ;;
     esac
     shift
@@ -229,7 +215,7 @@ done
 
 # Read and print stdin
 if [ $has_stdin = t ]; then
-    print_image "" 1 "$(cat | b64_encode)" 0 "$width" "$height" "$preserve_aspect_ratio" "$file_type"
+    print_image "" 1 "$(cat | b64_encode)" 0 "$width" "$height" "$preserve_aspect_ratio"
 fi
 
 if [ "$has_image_displayed" != "t" ]; then
