Update ALKS functions.

diff --git a/private_dot_config/private_fish/private_conf.d/private_80-config-alks.fish.tmpl b/private_dot_config/private_fish/private_conf.d/private_80-config-alks.fish.tmpl
--- a/private_dot_config/private_fish/private_conf.d/private_80-config-alks.fish.tmpl
+++ b/private_dot_config/private_fish/private_conf.d/private_80-config-alks.fish.tmpl
@@ -186,6 +186,37 @@ function alks-labs-224-creds -d "Write ALKS credentials file for Labs224"
     alks sessions open -i -r LabAdmin -a "{{ onepasswordRead "op://Work/ALKS Labs 224/notesPlain" }}" -o creds -f
 end
 
+function alks-ldark-np -d "Open ALKS session to LaunchDarkly non-production"
+    eval (alks sessions open -i -N -r Admin -a "{{ onepasswordRead "op://Work/ALKS LaunchDarkly Non-production/notesPlain" }}")
+end
+
+function alks-ldark-np-creds -d "Write ALKS credentials file for LaunchDarkly non-production"
+    alks sessions open -i -N -r Admin -a "{{ onepasswordRead "op://Work/ALKS LaunchDarkly Non-production/notesPlain" }}" -o creds -f
+end
+
+function alks-ldark-prod -d "Open ALKS session to LaunchDarkly production"
+    if test -z "$argv[1]"
+        echo "Missing CIID value" >&2
+        return 1
+    end
+    eval (alks sessions open -i -N -r Admin -a "{{ onepasswordRead "op://Work/ALKS LaunchDarkly Production/notesPlain" }}" \
+        --ciid $argv[1] \
+        --activity-type "Maintenance" \
+        --description "LaunchDarkly production admin session")
+end
+
+function alks-ldark-prod-creds -d "Write ALKS credentials file for LaunchDarkly production"
+    if test -z "$argv[1]"
+        echo "Missing CIID value" >&2
+        return 1
+    end
+    alks sessions open -i -N -r Admin -a "{{ onepasswordRead "op://Work/ALKS LaunchDarkly Production/notesPlain" }}" \
+        --ciid $argv[1] \
+        --activity-type "Maintenance" \
+        --description "LaunchDarkly production admin session" \
+        -o creds -f
+end
+
 function alks-splunk-np -d "Open ALKS session to Splunk non-production"
     eval (alks sessions open -i -N -r Admin -a "{{ onepasswordRead "op://Work/ALKS Splunk Non-production/notesPlain" }}")
 end
diff --git a/private_dot_zshrc.d/private_tools/private_alks.zsh.tmpl b/private_dot_zshrc.d/private_tools/private_alks.zsh.tmpl
--- a/private_dot_zshrc.d/private_tools/private_alks.zsh.tmpl
+++ b/private_dot_zshrc.d/private_tools/private_alks.zsh.tmpl
@@ -183,6 +183,37 @@ alks-labs-224-creds () {
     alks sessions open -i -r LabAdmin -a '{{ onepasswordRead "op://Work/ALKS Labs 224/notesPlain" }}' -o creds -f
 }
 
+alks-ldark-np () {
+    eval "$(alks sessions open -i -N -r Admin -a '{{ onepasswordRead "op://Work/ALKS LaunchDarkly Non-production/notesPlain" }}')"
+}
+
+alks-ldark-np-creds () {
+    alks sessions open -i -N -r Admin -a '{{ onepasswordRead "op://Work/ALKS LaunchDarkly Non-production/notesPlain" }}' -o creds -f
+}
+
+alks-ldark-prod () {
+    if [[ -z "$1" ]]; then
+        echo "Missing CIID value" >&2
+        return 1
+    fi
+    eval "$(alks sessions open -i -N -r Admin -a '{{ onepasswordRead "op://Work/ALKS LaunchDarkly Production/notesPlain" }}' \
+        --ciid "$1" \
+        --activity-type "Maintenance" \
+        --description "LaunchDarkly production admin session")"
+}
+
+alks-ldark-prod-creds () {
+    if [[ -z "$1" ]]; then
+        echo "Missing CIID value" >&2
+        return 1
+    fi
+    alks sessions open -i -N -r Admin -a '{{ onepasswordRead "op://Work/ALKS LaunchDarkly Production/notesPlain" }}' \
+        --ciid "$1" \
+        --activity-type "Maintenance" \
+        --description "LaunchDarkly production admin session" \
+        -o creds -f
+}
+
 alks-splunk-np () {
     eval "$(alks sessions open -i -N -r Admin -a '{{ onepasswordRead "op://Work/ALKS Splunk Non-production/notesPlain" }}')"
 }
